name: Dev Build PR
on: [pull_request_target, workflow_dispatch]
env:
  BUILD_TYPE: Release
permissions:
  contents: read
  pull-requests: read
jobs:
  dev-release:
    runs-on: windows-latest

    # Minimal permissions for this pull_request_target action
    # Because we only need to read the repository contents
    # By default, pull_request_target grants read/write permissions (not good)
    # But it also passes along repository secrets, which we need
    # unlike pull_request, which does not pass secrets
    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        target: [uevr]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          token: ${{ secrets.UESDK_PULLER || github.token }}
          submodules: recursive

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{matrix.target}}

      - name: Upload artifacts
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
        with:
          name: ${{matrix.target}}
          path: ${{github.workspace}}/build/bin/${{matrix.target}}/*
          if-no-files-found: error
